version: 11.0.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  sonarcloudorg: epinova
  sonarcloudproj: Epinova_Epinova.Associations
  sonarcloudkey:
    secure: 2ybvTGUPbPvQjW7RfcGGjBpFja97KJwSE/CmkCGaD7H1iLMWrKy5/PORO5CqFDIP
init:
- cmd: nuget sources add -Name Episerver -Source http://nuget.episerver.com/feed/packages.svc/
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
after_build:
pull_requests:
  do_not_increment_build_number: true
build:
  publish_nuget: true
  verbosity: minimal
cache:
  - packages -> **\packages.config
deploy:
  provider: NuGet
  api_key:
    secure: 6LdiQeX2LTezBZsshcBSJ2oUqVNDPkKj4y2VpHiM+wtg86SAJd/hzJl0mgavblhr
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: /^cms\d+$/
    APPVEYOR_REPO_BRANCH: /^cms\d+$/

# here we are going to override common configuration
for:

# override settings for `master` branch
-
  branches:
    only:
      - /^cms\d+$/

  before_build:
  - cmd: nuget restore
# Secure variables are not expanded in PR builds, hence the IF-tests
  - cmd: IF DEFINED sonarcloudkey choco install "sonarscanner-msbuild-net46" -y
  - cmd: IF DEFINED sonarcloudkey SonarScanner.MSBuild.exe begin /k:"%sonarcloudproj%" /d:"sonar.host.url=https://sonarcloud.io" /o:"%sonarcloudorg%" /d:"sonar.login=%sonarcloudkey%"
  after_build:
  - cmd: IF DEFINED sonarcloudkey SonarScanner.MSBuild.exe end /d:"sonar.login=%sonarcloudkey%"
